// <auto-generated />
using System;
using CRUDPLANILLA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUDPLANILLA.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CRUDPLANILLA.Models.HijoEmpleados", b =>
                {
                    b.Property<int>("Id_Registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Registro"), 1L, 1);

                    b.Property<int>("CantHijos")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id_Registro");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("HijoEmpleados");
                });

            modelBuilder.Entity("CRUDPLANILLA.Models.Planilla", b =>
                {
                    b.Property<int>("Id_Registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Registro"), 1L, 1);

                    b.Property<decimal>("IGSS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IRTRA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<decimal>("SalarioLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalarioTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Registro");

                    b.ToTable("Planilla");
                });

            modelBuilder.Entity("CRUDPLANILLA.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BonoDecreto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("NoDPI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordLogin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("CRUDPLANILLA.Models.HijoEmpleados", b =>
                {
                    b.HasOne("CRUDPLANILLA.Models.Usuario", null)
                        .WithMany("hijosEmpleado")
                        .HasForeignKey("UsuarioIdUsuario");
                });

            modelBuilder.Entity("CRUDPLANILLA.Models.Usuario", b =>
                {
                    b.Navigation("hijosEmpleado");
                });
#pragma warning restore 612, 618
        }
    }
}
